### ISSUE TITLE
[python3] 'KEY' in NormalizedDict().keys() / ('KEY', value) in NormalizedDict().items()

### ISSUE THREAD

**Issue by userzimmermann** [userzimmermann/robotframework#11]
In Python 2, `NormalizedDict().keys()` and `NormalizedDict().items()` return **lists** with normalized keys, which causes the following behavior:

```
>>> nd = NormalizedDict('key': 'value')
>>> nd['key']
'value'
>>> nd['KEY']
'value'
>>> nd.keys()
['key']
>>> 'key' in nd.keys()
True
>>>> 'KEY' in nd.keys()
False
>>> nd.items()
[('key', 'value')]
>>> ('key', 'value') in nd.items()
True
>>> ('KEY', 'value') in nd.items()
False
```

In Python 3, since `NormalizedDict` is based on `MutableMapping`, `NormalizedDict().keys()` returns `KeysView` instances and `NormalizedDict().items()` returns `ItemsView` instances. Their `__contains__` methods use `NormalizedDict.__getitem__` for lookup, which results in the following different behavior:

```
>>> nd.keys()
KeysView(<robot.utils.normalizing.NormalizedDict object at 0x...>)
>>> list(nd.keys())
['key']
>>> 'key' in nd.keys()
True
>>>> 'KEY' in nd.keys()
True
>>> nd.items()
ItemsView(<robot.utils.normalizing.NormalizedDict object at 0x...>)
>>> list(nd.items())
[('key', 'value')]
>>> ('key', 'value') in d.items()
True
>>> ('KEY', 'value') in d.items()
True
```

Since this behavior is checked in `TestNormalizedDict` in the unit tests, it leads to FAILs in Python 3. Is it better to override `.keys()` and `.items()` to restore the Python 2 behavior or leave it that way with respect to the different return types of `.keys()` and `.items()` in Python 3 and adjust the unit tests?

**Comment by pekkaklarck** [comment]
First of all, are you using the latest `NormalizedDict` version? I just changed it to use `MutableMapping` instead of `UserDict` few days ago.

I would say it's better to keep `NormalizedDict` as it is and updated unit tests. I would assume it's enough in many/most/all places to just replace `nd.keys()` with `list(nd.keys())`.

**Comment by userzimmermann** [comment]
The problem was introduced with the `MutableMapping` base.

I already replaced with `list(nd.keys())` and `list(nd.items())` in the most cases. I also generally think that the methods not returning lists anymore should just be accepted as Python 3 standard. Actually the question is only if it's somehow important that `'KEY' in nd.keys()` is `False` for keys not in their original form, which isn't the case anymore in Python 3 (and it's explicitly tested in `test_update` and `test_update_using_another_norm_dict`). But I also think that should be accepted in the same way and is just a matter of getting a list or not.

@pekkaklarck Thanks for your comment.

**Comment by pekkaklarck** [comment]
I don't think `'KEY' in nd.keys()` is that important. Haven't looked at those tests now, but I guess they are just verifying that if you do

``` python
nd = NormalizedDict()
nd['key'] = 1
nd['KEY'] = 2
```

you just have one item in that dict and that the initial key is preserved.

**Comment by userzimmermann** [comment]
These are the actual tests:

```
def test_update(self):
    nd = NormalizedDict({'a': 1, 'b': 1, 'c': 1})
    nd.update({'b': 2, 'C': 2, 'D': 2})
    for c in 'bcd':
        assert_equals(nd[c], 2)
        assert_equals(nd[c.upper()], 2)
    assert_true('b' in nd.keys())
    assert_true('c' in nd.keys())
    assert_true('C' not in nd.keys())
    assert_true('d' not in nd.keys())
    assert_true('D' in nd.keys())

def test_update_using_another_norm_dict(self):
    nd = NormalizedDict({'a': 1, 'b': 1})
    nd.update(NormalizedDict({'B': 2, 'C': 2}))
    for c in 'bc':
        assert_equals(nd[c], 2)
        assert_equals(nd[c.upper()], 2)
    assert_true('b' in nd.keys())
    assert_true('B' not in nd.keys())
    assert_true('c' not in nd.keys())
    assert_true('C' in nd.keys())
```

And the `not in`s are the actual problem.

**Comment by userzimmermann** [comment]
I will also just `list(nd.keys())` for the `not in` checks.

**Comment by pekkaklarck** [comment]
I'd actually change the tests like this:

``` python
keys = list(nd)
assert_true('b' in keys)
assert_true('c' in keys)
assert_true('C' not in keys)
```

**Comment by userzimmermann** [comment]
@pekkaklarck Would you like to change that in the main repo?

**Comment by pekkaklarck** [comment]
Sure. Can you create a PR? No issue needed for test changes.

**Comment by userzimmermann** [comment]
Will do.

**Comment by userzimmermann** [comment]
Resolved by https://github.com/robotframework/robotframework/issues/2006
