### ISSUE TITLE
[python3]:failed to install robotframework-databaselibrary using robotframework-python3

### ISSUE THREAD

**Issue by xidianlp** [userzimmermann/robotframework#12]
hi,
I updated my python from 2.7.9 to 3.4.3, and then installed robotframework-python3. When I try to install robotframework-databaselibrary, it told me "ImportError: No module named 'connection_manager'". How to fix this issue? I updated my python version to 3.4.3, it is because I meet the error "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 51: ordinal not in range" when I run my auto test in Linux, but it is ok in Windows.

**Comment by userzimmermann** [comment]
Hi. And sorry for the late answer :)
**robotframework-databaselibrary** is just not **Python 3** compatible yet, as most of the Test Libraries out there...
